// SPDX-License-Identifier: MIT
pragma solidity ^0.8.36;

import {Test} from "../lib/forge-std/src/Test.sol";
import {LibString} from "../lib/solady/src/utils/LibString.sol";
import {TokenList} from "../src/utils/TokenList.sol";
import {TokenListLens} from "../src/utils/TokenListLens.sol";
import {TokenListRenderer} from "../src/utils/TokenListRenderer.sol";
import {PostDeployListings} from "./PostDeployListings.sol";

/// @notice Proves — and emits — the owner transactions that finish the token list.
/// @dev `TokenList`'s constructor seeds four entries because eleven no longer fit
///      under EIP-7825's 16,777,216-gas per-transaction cap. The other seven are
///      applied here, by the owner, after deployment. This suite is the bridge
///      between those two facts:
///
///        1. It applies the seven against a mainnet fork and asserts the result is
///           byte-for-byte the list the eleven-token constructor used to produce —
///           same ids, same order, same pulled text, same art, same standards.
///        2. It writes the exact calldata for those transactions to
///           `deploy/TokenList.postdeploy.calldata.txt`, so what gets broadcast is
///           generated by the run that verified it rather than hand-assembled next
///           to it.
///        3. It asserts every one of those transactions fits under the same gas cap
///           that forced the split, because a seeding plan that cannot be mined is
///           no better than a constructor that cannot be deployed.
///
///      Run with: forge test --match-contract TokenListPostDeploy
contract TokenListPostDeployTest is Test, PostDeployListings {
    using LibString for string;

    /// @dev EIP-7825. The same ceiling that forced the constructor split; a batch
    ///      that exceeds it is unmineable no matter how large the block is.
    uint256 constant TX_GAS_CAP = 16_777_216;

    TokenList list;
    TokenListLens lens;
    TokenListRenderer renderer;
    address owner = address(0xA11CE);

    function setUp() public {
        renderer = new TokenListRenderer();
        list = new TokenList(owner, renderer);
        lens = new TokenListLens();
    }

    /// @dev The constructor's half of the split, restated here so the two halves are
    ///      asserted against each other in one place.
    function testConstructorSeedsExactlyTheFourThatFit() public view {
        assertEq(list.total(), 4);
        string[4] memory expected = ["ETH", "WETH", "USDC", "USDT"];
        uint256[] memory ranked = lens.rankedIds(list);
        for (uint256 i; i < expected.length; ++i) {
            assertEq(list.get(ranked[i]).symbol, expected[i]);
        }
    }

    /// @dev Each listing is one `multicall` — list, set the art, and for a collection
    ///      set the onchain-SVG hint — so a token is either fully on the list or not
    ///      on it at all. A half-applied listing would sit in the registry with no
    ///      logo, which is exactly the broken-looking card the art exists to prevent.
    function testPostDeployListingsAreAppliedAndFitTheGasCap() public {
        Listing[] memory l = _postDeployListings();
        uint256 total;

        for (uint256 i; i < l.length; ++i) {
            bytes[] memory calls = _callsFor(l[i]);
            vm.prank(owner);
            uint256 before = gasleft();
            list.multicall(calls);
            uint256 used = before - gasleft();
            total += used;

            emit log_named_uint(string.concat("gas  ", list.get(l[i].token).symbol), used);
            assertLt(used, TX_GAS_CAP, "one listing must fit one transaction");

            TokenList.Token memory t = list.get(l[i].token);
            assertEq(t.rank, l[i].rank);
            assertEq(t.color, l[i].color);
            assertEq(t.url, l[i].url);
            assertEq(t.description, l[i].description);
            assertEq(t.onchainSvg, l[i].onchainSvg);
            assertEq(uint8(t.standard), uint8(l[i].expectedStandard));
            assertTrue(t.synced, "text must come from the token, not from this file");
            assertTrue(t.logo.startsWith("data:image/svg+xml;base64,"));
        }
        emit log_named_uint("gas  ALL SEVEN", total);
    }

    /// @dev The point of the whole exercise: after the seven, the list is the one
    ///      that was reviewed and mined for, not a reduced version of it.
    function testAppliedListMatchesTheOriginalEleven() public {
        _applyAll();

        assertEq(list.total(), 11);
        string[11] memory expected =
            ["ETH", "WETH", "wstETH", "rETH", "WBTC", "USDC", "USDT", "BOLD", "ZORG", "zzz", "WEI"];
        uint32[11] memory ranks = [
            uint32(1_000_000), 999_000, 998_000, 997_000, 996_000, 995_000, 994_000, 993_000, 992_000, 991_000, 990_000
        ];

        uint256[] memory ranked = lens.rankedIds(list);
        for (uint256 i; i < expected.length; ++i) {
            TokenList.Token memory t = list.get(ranked[i]);
            assertEq(t.symbol, expected[i]);
            assertEq(t.rank, ranks[i], "the sparse gaps must place these without renumbering");
            // Every card must render; a listing whose tokenURI reverts is worse than
            // an absent one, because it breaks the gallery rather than shortening it.
            assertTrue(list.tokenURI(ranked[i]).startsWith("data:application/json;base64,"));
            assertTrue(bytes(list.logoOf(ranked[i])).length > 100, "real art, not a stub");
        }

        // The registry holds only what has no address here: the native asset.
        assertEq(list.ownerOf(list.idOf(address(0))), address(list));
        assertEq(list.ownerOf(list.idOf(WBTC)), WBTC);
    }

    /// @dev The two collections are the only listings whose standard is detected
    ///      rather than declared, and the only ones carrying the onchain-SVG hint.
    function testCollectionsSurviveThePostDeployRoute() public {
        _applyAll();
        for (uint256 i; i < 2; ++i) {
            address c = i == 0 ? ZORGZ : WNS;
            TokenList.Token memory t = list.get(c);
            assertEq(uint8(t.standard), uint8(TokenList.Standard.ERC721));
            assertTrue(t.onchainSvg);
            assertEq(t.decimals, 0);
            assertTrue(list.json(list.idOf(c)).contains('"p":"ERC-721"'));
        }
    }

    /// @dev Writes the broadcast payload. One line per transaction, in apply order.
    function testWritePostDeployCalldata() public {
        Listing[] memory l = _postDeployListings();
        string memory out = string.concat(
            "# TokenList post-deploy listings\n",
            "#\n",
            "# Owner transactions that add the seven entries the constructor cannot\n",
            "# afford under EIP-7825's 16,777,216-gas per-transaction cap.\n",
            "# Send IN ORDER to `TokenList`, from the owner. Each line is one\n",
            "# `multicall` bundling list + setLogoSVG (+ setOnchainSvg for a\n",
            "# collection), so a listing never lands without its art.\n",
            "#\n",
            "# GENERATED by test/TokenListPostDeploy.t.sol - do not hand-edit.\n"
        );

        for (uint256 i; i < l.length; ++i) {
            bytes[] memory calls = _callsFor(l[i]);
            bytes memory cd = abi.encodeWithSignature("multicall(bytes[])", calls);
            vm.prank(owner);
            list.multicall(calls);
            out = string.concat(
                out,
                "\n# ",
                LibString.toString(i + 1),
                ". ",
                list.get(l[i].token).symbol,
                "  ",
                LibString.toHexStringChecksummed(l[i].token),
                "  rank ",
                LibString.toString(l[i].rank),
                "\n",
                LibString.toHexString(cd),
                "\n"
            );
        }

        vm.writeFile("deploy/TokenList.postdeploy.calldata.txt", out);
        assertEq(list.total(), 11);
    }

    function _callsFor(Listing memory e) internal pure returns (bytes[] memory calls) {
        uint256 id = uint256(uint160(e.token)); // a local listing id IS its address
        calls = new bytes[](e.onchainSvg ? 3 : 2);
        calls[0] = abi.encodeWithSignature(
            "list(address,uint24,uint32,string,string,string)", e.token, e.color, e.rank, "", e.url, e.description
        );
        calls[1] = abi.encodeWithSignature("setLogoSVG(uint256,string)", id, e.logo);
        if (e.onchainSvg) calls[2] = abi.encodeWithSignature("setOnchainSvg(uint256,bool)", id, true);
    }

    function _applyAll() internal {
        Listing[] memory l = _postDeployListings();
        for (uint256 i; i < l.length; ++i) {
            vm.prank(owner);
            list.multicall(_callsFor(l[i]));
        }
    }
}
