// SPDX-License-Identifier: MIT
pragma solidity ^0.8.36;

import {LibString} from "../../lib/solady/src/utils/LibString.sol";

interface IMolochMeta {
    function name(uint256) external view returns (string memory);
    function symbol(uint256) external view returns (string memory);
}

interface IBaseRenderer {
    function daoContractURI(address dao) external view returns (string memory);
    function daoTokenURI(address dao, uint256 id) external view returns (string memory);
}

/// @dev The renderer every zFi DAO points at today. It returns the Wyoming DUNA
/// covenant — a fully on-chain document that reads the DAO's live share supply and
/// its real transfer/ragequit flags at call time.
address constant BASE_RENDERER = 0x000000000011C799980827F52d3137b4abD6E654;

/// @title DUNABrandRenderer
/// @notice Lets a DAO carry BOTH the on-chain DUNA covenant and its own branding
///         through the single `contractURI()` slot.
///
/// @dev Moloch.contractURI() returns the stored `_orgURI` when it is set and only
/// falls through to the renderer when it is empty:
///
///     function contractURI() public view returns (string memory) {
///         string memory orgURI = _orgURI;
///         if (bytes(orgURI).length != 0) return orgURI;   // <- short-circuit
///         ...
///         return IMajeurRenderer(_r).daoContractURI(this);
///     }
///
/// So a DAO that pins its metadata to IPFS and passes it as `orgURI` displaces the
/// covenant entirely, and a DAO that wants the covenant has to give up its branding.
/// The slot holds one document; the choice looks binary.
///
/// It is only binary if the branding lives OFF the renderer. This contract inverts
/// that: the DAO summons with an EMPTY `orgURI` (so `contractURI()` reaches the
/// renderer) and registers its pinned metadata here instead. The composed document
/// carries the branding fields a marketplace or the zFi coin page needs, and links
/// the live covenant as `charter_uri`, which is regenerated by BASE_RENDERER on
/// every read and therefore cannot go stale the way a pinned snapshot does.
///
/// Storage is deliberately two URIs and a type tag rather than the full metadata
/// document. `image` is what a reader must have inline to render a token list row;
/// everything else (banner, description, socials) is already in the pinned JSON that
/// `external_url` points at, and a client that wants it was going to fetch that
/// document anyway. Putting the rest on-chain would cost several hundred thousand
/// gas at summon time to save a fetch nobody saves.
///
/// A DAO that registers nothing gets the unmodified covenant, so pointing an
/// existing DAO's renderer here is safe before its branding is set.
contract DUNABrandRenderer {
    using LibString for string;

    error EmptyLaunchType();

    event BrandingSet(address indexed dao, string metadata, string image, string launchType);

    struct Brand {
        string metadata; // pinned document (ipfs://…) — surfaced as external_url
        string image; // logo URI, inlined so a list row renders without a fetch
        string launchType; // routing tag, e.g. "cause" — see the note on _compose()
    }

    mapping(address dao => Brand) internal _brand;

    /// @notice Register branding for the calling DAO.
    /// @dev Keyed by msg.sender, which is what makes this callable from Moloch's
    ///      `initCalls`: those execute from the DAO's own context during summon
    ///      (Moloch.init loops `initCalls[i].target.call(...)`), so a DAICO can seed
    ///      its branding in the summoning transaction with no extra tx and no extra
    ///      signature. Afterwards the same call is reachable through governance,
    ///      since a passed proposal also executes as the DAO.
    function setBranding(string calldata metadata, string calldata image, string calldata launchType) public {
        if (bytes(launchType).length == 0) revert EmptyLaunchType();
        _brand[msg.sender] = Brand(metadata, image, launchType);
        emit BrandingSet(msg.sender, metadata, image, launchType);
    }

    /// @notice Clear the calling DAO's branding, reverting it to the bare covenant.
    function clearBranding() public {
        delete _brand[msg.sender];
        emit BrandingSet(msg.sender, "", "", "");
    }

    function branding(address dao) public view returns (Brand memory) {
        return _brand[dao];
    }

    /// @notice ERC-7572 contract-level metadata: covenant + branding in one document.
    /// @dev Falls through to the bare covenant when the DAO has registered nothing.
    function daoContractURI(address dao) public view returns (string memory) {
        Brand memory b = _brand[dao];
        if (bytes(b.launchType).length == 0) {
            return IBaseRenderer(BASE_RENDERER).daoContractURI(dao);
        }
        return _compose(dao, b);
    }

    /// @notice Per-token metadata is untouched — the base renderer draws proposal art,
    ///         which branding has nothing to say about.
    function daoTokenURI(address dao, uint256 id) public view returns (string memory) {
        return IBaseRenderer(BASE_RENDERER).daoTokenURI(dao, id);
    }

    /// @dev Every interpolated value is DAO-controlled, so all of them are escaped.
    /// `name`/`symbol` are set by whoever summoned the DAO and `metadata`/`image`/
    /// `launchType` by whoever called setBranding — an unescaped quote in any of them
    /// would let the DAO inject arbitrary keys into its own metadata document, which a
    /// consumer would read as authentic on-chain fields.
    ///
    /// `launchType` is echoed rather than fixed to "cause" because it is what the coin
    /// page routes on (`metadata.launchType === 'cause'` picks the sale UI over the
    /// generic DAO page). A composed document that dropped it would render a DAICO as
    /// a plain treasury: no buy form, no funding meter, no tap panel.
    function _compose(address dao, Brand memory b) internal view returns (string memory) {
        string memory charter = IBaseRenderer(BASE_RENDERER).daoContractURI(dao);
        return string.concat(
            "data:application/json;utf8,{",
            '"name":', LibString.escapeJSON(IMolochMeta(dao).name(0), true),
            ',"symbol":', LibString.escapeJSON(IMolochMeta(dao).symbol(0), true),
            ',"description":"Wyoming Decentralized Unincorporated Nonprofit Association',
            " operating charter and member agreement. The full covenant is rendered",
            ' on-chain; see charter_uri.",',
            '"image":', LibString.escapeJSON(b.image, true),
            ',"launchType":', LibString.escapeJSON(b.launchType, true),
            ',"charter":"duna"',
            ',"charter_uri":', LibString.escapeJSON(charter, true),
            ',"external_url":', LibString.escapeJSON(b.metadata, true),
            "}"
        );
    }
}
