[profile.default]
src = "/Users/z/zFi/src"
test = "/Users/z/zFi/test"
out = "/Users/z/zFi/out"
libs = ["/Users/z/zFi/lib"]
remappings = ["src/=/Users/z/zFi/src/", "test/=/Users/z/zFi/test/"]
solc = "0.8.36"
evm_version = "prague"
via_ir = true
optimizer = true
optimizer_runs = 9999999
gas_limit = "18446744073709551615"
